helm:
  parameters:
  - name: image.name
    value: ghcr.io/kaikiat/fyp-ci
    forcestring: true
  - name: image.tag
    # value: 0.3.27
    # value: 0.3.33
    # value: 0.3.36
    # value: 0.3.28
    # value: 0.3.29
    value: 0.3.36
    # value: 0.3.37
    # value: 0.3.35
    forcestring: true
