apiVersion: v1
kind: Secret
metadata:
  name: environment-variables-workers-secret
#  namespace: default
type: Opaque
stringData:
  # MASTER: sgdecoding-staging-master
  MASTER: sgdecoding-staging-master-preview
  NAMESPACE: default
  RUN_FREQ: FOREVER # for run_worker.yaml (testing) will override this with value=ONCE
  ENABLE_HTTPS: "false"
  MODELS_FILESHARE_SECRET: models-files-secret
  MODELS_SHARE_NAME: online-models
  IMAGE: abcd


---

apiVersion: v1
kind: Secret
metadata:
  name: environment-variables-master-secret
#  namespace: default
type: Opaque
stringData:
  NAMESPACE: default
  # MASTER: sgdecoding-staging-master
  MASTER: sgdecoding-staging-master-preview
  ENABLE_HTTPS: "false"
  MODELS_FILESHARE_SECRET: models-files-secret
  MODELS_SHARE_NAME: online-models
  IMAGE: abcd