apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "ntuspeechlab.master.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "ntuspeechlab.master.name" . }}
    helm.sh/chart: {{ include "ntuspeechlab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ntuspeechlab.master.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%" # The maximum number of replicas the rollout can create 
      maxUnavailable: 0 # The maximum number of pods that can be unavailable during the update.
      analysis:
        templates:
        - templateName: analyse-request
        startingStep: 2
        args:
          - name: service-name
            value: prometheus-kube-prometheus-prometheus.default.svc.cluster.local
      steps:
      - pause:
        duration: 100s 
      - setWeight: 50
      - pause:
          duration: 100s 
      - setWeight: 90
      - pause: 
          duration: 100s 
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '8081'
      labels:
        app.kubernetes.io/name: {{ include "ntuspeechlab.master.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      containers:
        - name: {{ include "ntuspeechlab.master.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [{{ include "ntuspeechlab.master.command" . }}]
          envFrom:
          - secretRef:
              name: environment-variables-master-secret
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              name: metrics
              protocol: TCP          
          livenessProbe:
            httpGet:
              path: /
              {{- if eq .Values.service.enablehttps true}}
              scheme: HTTPS
              port: 8080
              {{- else }}
              port: http
              {{- end}}
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              {{- if eq .Values.service.enablehttps true}}
              scheme: HTTPS
              port: 8080
              {{- else }}
              port: http
              {{- end}}
            periodSeconds: 60
{{- range $model_name, $replicas := .Values.models }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "ntuspeechlab.worker.name" $ }}{{ printf "-%s" $model_name | lower | replace "_" "-"  }}
  labels:
    app.kubernetes.io/name: {{ include "ntuspeechlab.worker.name" $ }}{{ printf "-%s" $model_name | lower | replace "_" "-" }}
    helm.sh/chart: {{ include "ntuspeechlab.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ntuspeechlab.worker.name" $ }}{{ printf "-%s" $model_name  | lower | replace "_" "-"}}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%" # The maximum number of replicas the rollout can create 
      maxUnavailable: 0 # The maximum number of pods that can be unavailable during the update.
      analysis:
        templates:
        - templateName: analyse-request
        args:
          - name: service-name
            value: prometheus-kube-prometheus-prometheus.default.svc.cluster.local
        startingStep: 2
      steps:
      - pause:
        duration: 100s 
      - setWeight: 50s
      - pause:
          duration: 100s
      - setWeight: 90
      - pause: 
          duration: 100s
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
      labels:
        app.kubernetes.io/name: {{ include "ntuspeechlab.worker.name" $ }}{{ printf "-%s" $model_name | lower | replace "_" "-" }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ $.Values.image.pullSecrets }}
      containers:
        - name: {{ include "ntuspeechlab.worker.name" $ }}{{ printf "-%s" $model_name | lower  | replace "_" "-"}}
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: [{{ include "ntuspeechlab.worker.command" $ }}]
          envFrom:
          - secretRef:
              name: environment-variables-workers-secret
          env:
          - name: MODEL_DIR
            value: {{ $model_name }}
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
          - name: mypvc
            mountPath: /home/appuser/opt/models
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: {{ $.Values.fileshare.claimName }}
{{- end }}
