apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: ntuasr=ghcr.io/kaikiat/fyp-ci
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main:image-updater{{range .Images}}-{{.Name}}-{{.NewTag}}{{end}}
  name: sgdecoding-online-scaled 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kaikiat/fyp-cd.git  
    targetRevision: main  
    path: blue_green/sgdecoding-online-scaled  
    # path: canary/sgdecoding-online-scaled 
  destination:
    server: https://kubernetes.default.svc
    namespace: ntuasr-production-google
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
      allowEmpty: false 
    syncOptions:    
    - Validate=false
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 

