models:
  SingaporeCS_0519NNET3: 1
  # SingaporeMandarin_0519NNET3: 0
  
image:
  # getting credentials: exec: exec: "aws": executable file not found in $PATH
  # repository: ghcr.io/kaikiat/fyp-ci:0.3.0  # import ws4 error in client.py
  # repository: ghcr.io/kaikiat/fyp:latest
  # repository: ghcr.io/kaikiat/fyp-1:latest
  # repository: ghcr.io/kaikiat/kaikiat/kaikiat/fyp-1:latest
  repository: ghcr.io/kaikiat/ntu-asr-image:latest
  pullPolicy: Always
  pullSecrets: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080
  resourceGroup: ntu-online-scaled
  enablehttps: false

commands:
  master:
    - '"/home/appuser/opt/tini"' 
    - '"--"'
    - '"/home/appuser/opt/start_master.sh"'
  worker:
  # see _helpers.tpl on how full command constructed
    pre:
      - '"/home/appuser/opt/tini"' 
      - '"--"'
      - '"/home/appuser/opt/start_worker.sh"'
fileshare:
  claimName: fileserver-claim
