helm:
  parameters:
  - name: image.name
    value: ghcr.io/kaikiat/fyp-ci
    forcestring: true
  - name: image.tag
    # value: 0.3.36
    # value: 0.3.33
    # value: 0.3.35
    value: 0.3.38
    # value: 0.3.39
    forcestring: true
