apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-example-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2 #default value is 1
      maxUnavailable: 0 #default value is 1
      