metadata:
  labels:
    app: rollout-demo
  name: rollout-demo
  annotations:
    a8r.io/description: Demo service to try the rollout feature
    a8r.io/owner: Ambassador Labs
    a8r.io/documentation: https://www.getambassador.io/docs/cloud/latest/service-catalog/howtos/rollout/
    a8r.io/repository: git@github.com:kaikiat/fyp-cd.git    
