apiVersion: argoproj.io/v1alpha1
kind: Rollout
# apiVersion: apps/v1
# kind: Deployment
metadata:
  name: {{ include "ntuspeechlab.master.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "ntuspeechlab.master.name" . }}
    helm.sh/chart: {{ include "ntuspeechlab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ntuspeechlab.master.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  # Add strategy here
  strategy:
    blueGreen: 
      activeService: {{ include "ntuspeechlab.master.name" . }}
      previewService: {{ include "ntuspeechlab.master.name" . }}-preview #  to test a new version of an application.
  #     autoPromotionEnabled: false #  make the rollout automatically promote the new ReplicaSet to the active service once the new ReplicaSet is healthy
      # autoPromotionEnabled: true #  make the rollout automatically promote the new ReplicaSet to the active service once the new ReplicaSet is healthy
      # scaleDownDelaySeconds: 150 # delay scaling down the old ReplicaSet after the active Service is switched
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
      labels:
        app.kubernetes.io/name: {{ include "ntuspeechlab.master.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      containers:
        - name: {{ include "ntuspeechlab.master.name" . }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [{{ include "ntuspeechlab.master.command" . }}]
          envFrom:
          - secretRef:
              name: environment-variables-master-secret
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: prometheus
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /
              {{- if eq .Values.service.enablehttps true}}
              scheme: HTTPS
              port: 8080
              {{- else }}
              port: http
              {{- end}}
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              {{- if eq .Values.service.enablehttps true}}
              scheme: HTTPS
              port: 8080
              {{- else }}
              port: http
              {{- end}}
            periodSeconds: 60
---
# apiVersion: apps/v1
# kind: Deployment
# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
metadata:
  name: sgdecoding-online-scaled-worker-singaporecs-0519nnet3
  labels:
    app.kubernetes.io/name: {{ include "ntuspeechlab.worker.name" $ }}
    helm.sh/chart: {{ include "ntuspeechlab.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ntuspeechlab.worker.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  # Add strategy here
  strategy:
    blueGreen: 
      activeService: {{ include "ntuspeechlab.master.name" . }}
      previewService: {{ include "ntuspeechlab.master.name" . }}-preview #  to test a new version of an application.
      autoPromotionEnabled: false #  make the rollout automatically promote the new ReplicaSet to the active service once the new ReplicaSet is healthy
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
      labels:
        app.kubernetes.io/name: {{ include "ntuspeechlab.worker.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ $.Values.image.pullSecrets }}
      containers:
        - name: {{ include "ntuspeechlab.worker.name" $ }}
          image: {{ $.Values.image.repository }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: [{{ include "ntuspeechlab.worker.command" $ }}]
          envFrom:
          - secretRef:
              name: environment-variables-workers-secret
          ports:
            - name: prometheus
              containerPort: 8081
          env:
          - name: MODEL_DIR
            value: SingaporeCS_0519NNET3
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
          - name: mypvc
            mountPath: /home/appuser/opt/models

      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: {{ $.Values.fileshare.claimName }}
