apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.image-updater: apiKey
  registries.conf: |
    registries:
      - name: GitHub Container Registry
        api_url: https://docker.pkg.github.com
        ping: no
        tagsortmode: latest_first
        credentials: git:secret:argocd/git-creds


