helm:
  parameters:
  - name: image.name
    value: ghcr.io/kaikiat/python-docker
    forcestring: true
  - name: image.tag
    # value: 0.0.8
    # value: 0.0.5
    value: 0.0.7
    forcestring: true
