models:
  SingaporeCS_0519NNET3: 1
  SingaporeMandarin_0519NNET3: 0
  
image:
  repository: ghcr.io/kaikiat/{{github.repository}}:0.3.0
  # repository: ghcr.io/kaikiat/ntu-asr-image:latest
  pullPolicy: Always
  pullSecrets: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080
  resourceGroup: ntu-online-scaled
  enablehttps: false

commands:
  master:
    - '"/home/appuser/opt/tini"' 
    - '"--"'
    - '"/home/appuser/opt/start_master.sh"'
  worker:
  # see _helpers.tpl on how full command constructed
    pre:
      - '"/home/appuser/opt/tini"' 
      - '"--"'
      - '"/home/appuser/opt/start_worker.sh"'
fileshare:
  claimName: fileserver-claim
