apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: analyse-request
spec:
  metrics:
  - name: analyse-request
    interval: 20s
    successCondition: result[0] < 0.35 || isNaN(result[0])
    failureLimit: 4
    provider:
      prometheus:
        address: http://34.124.209.46:9090
        query: |
          sum(number_of_request_reject_total{service="sgdecoding-online-scaled-master"})/sum(number_of_request_receive_by_master_total{service="sgdecoding-online-scaled-master"}) % 0.1
          # sum(number_of_request_receive_by_master_total{service="sgdecoding-online-scaled-master"})/sum(number_of_request_reject_total{service="sgdecoding-online-scaled-master"})
