apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: analyse-request
spec:
  metrics:
  - name: analyse-request
    interval: 30s
    # successCondition: result[0] >= 1 || isNaN(result[0])
    successCondition: result[0] < 0.1 || isNaN(result[0])
    failureLimit: 4
    provider:
      prometheus:
        # address: http://34.143.143.67:9090 # (ntu-16)
        address: http://34.124.209.46:9090 # (nonscriberabbit)
        query: |
          # sum(number_of_request_receive_by_master_total{service="sgdecoding-online-scaled-master"})/sum(number_of_request_reject_total{service="sgdecoding-online-scaled-master"})
          sum(number_of_request_reject_total{service="sgdecoding-online-scaled-master"})/sum(number_of_request_receive_by_master_total{service="sgdecoding-online-scaled-master"})
