apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= 1
    failureLimit: 3
    provider:
      prometheus:
        # address: localhost:9090
        address: http://34.143.143.67:9090
        query: |
          sum(number_of_worker_available{service="sgdecoding-online-scaled-master"})

