apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-deployment
spec:
  selector:
    matchLabels:
      app: flask-k8s
  template:
    metadata:
      labels:
        app: flask-k8s
    spec:
      containers:
        - name: flask-k8s
          image: {{ .Values.image.repository }}:{{ .Values.images.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
