apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sgdecoding-online-scaled-master
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sgdecoding-online-scaled-master
  podMetricsEndpoints:
  - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sgdecoding-online-scaled-worker-singaporecs-0519nnet3
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sgdecoding-online-scaled-worker-singaporecs-0519nnet3
  podMetricsEndpoints:
  - port: metrics