apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sgdecoding-online-scaled-master-preview
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sgdecoding-online-scaled-master-preview
  endpoints:
  - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sgdecoding-online-scaled-worker-singaporecs-0519nnet3-preview
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sgdecoding-online-scaled-worker-singaporecs-0519nnet3-preview
  endpoints:
  - port: metrics